### ISSUE TITLE
I want to play webrtc-chord

### ISSUE THREAD

**Issue by matsumotory** [tsujio/webrtc-chord#1]
Hi, @tsujio 

webrtc-chord is very interesting. I want to try your webrtc-chord, but install document is nothing. So, Could you add more detail for install into `README.md`?

**Comment by tsujio** [comment]
Sorry, but I'm writing README.md just now, so would you wait until the completion? Preparing English document is very hard for me X(

**Comment by matsumotory** [comment]
Thanks for your response. OK, I'm wating.

**Comment by tsujio** [comment]
Hi, @matsumoto-r 

I have updated README.md and described simple usages of webrtc-chord and chord-monitor in it.
Please try them.

I appreciate your advice.

**Comment by matsumotory** [comment]
Oh, i'ts great work! Thanks.
