### ISSUE TITLE
Use PeerJS's new hooks

### ISSUE THREAD

**Issue by jure** [tsujio/webrtc-chord#13]
A new version of PeerJS was just released (https://github.com/peers/peerjs/pull/217), and it includes hooks/events for when clients are disconnected from the signalling server:

```
'disconnected' EVENT peer.on('disconnected', function() { ... });
Emitted when the peer is disconnected from the signalling server, 
either manually or because the connection to the signalling server was lost. 
When a peer is disconnected, its existing connections will stay alive, but the 
peer cannot accept or create any new connections. You can reconnect to 
the server by calling peer.reconnect().
```

and corresponding errors too: 

```
'network' ERROR
Lost or cannot establish a connection to the signalling server.
```

It would be a good thing to use these from within webrtc-chord, to improve resilience with respect to network/connection instability.

**Comment by tsujio** [comment]
Thank you. I'll introduce it.

**Comment by jure** [comment]
Done in https://github.com/tsujio/webrtc-chord/commit/ae2de22ea8b0c2cb203612d298b01bb562eee262
