### ISSUE TITLE
Blog post about a project with webrtc-chord

### ISSUE THREAD

**Issue by jure** [tsujio/webrtc-chord#4]
You might have noticed a nice uptick in the number of watchers/stars. I've used your Chord DHT for a project and I've posted a blog post yesterday evening (with proper attribution to you, the author of webrtc-chord). It has been very well received (#6 on front page of Hackernews), so I thought you might like to read it yourself: http://juretriglav.si/an-open-distributed-search-engine-for-science/

Thank you for your work, it's fantastic, and my project would not be possible without it!

**Comment by tsujio** [comment]
I have read your article and it is very interesting! I will install Scholar Ninja and try it.
This is the first contribution of my OSS activity, so I really feel pleasure and appreciate your report.

Thank you.
